os: unstable
cache:
  - node_modules
environment:
  GH_TOKEN:
      secure: ruXayOUgryDqMg8KBrkEVzK3WZCvh+nJq1ZVA8NRylHdeQQDQO44wfyBf0Bi9ZUt
  matrix:
    - nodejs_version: 8
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - yarn install
matrix:
  fast_finish: true
build: off
version: '{branch}-{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - yarn release-appveyor