os: unstable
cache:
  - node_modules
environment:
  GH_TOKEN:
      secure: 5JStucvOwanG2EdXQbwR6e0usn2eOgSetxdgKOU76V+WKAnzXAx5Mr61Z4pTEEzk
  matrix:
    - nodejs_version: 8
install:
  - ps: Install-Product node $env:nodejs_version
  - set CI=true
  - yarn install
matrix:
  fast_finish: true
build: off
version: '{branch}-{build}'
shallow_clone: true
clone_depth: 1
test_script:
  - yarn release-appveyor
